function Hd = irr_elliptic_200_800
%IRR_ELLIPTIC_200_800 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.10 and Signal Processing Toolbox 8.6.
% Generated on: 02-Nov-2021 10:51:10

% Elliptic Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = 10000;  % Sampling Frequency

N      = 2;    % Order
Fpass1 = 200;  % First Passband Frequency
Fpass2 = 800;  % Second Passband Frequency
Apass  = 1;    % Passband Ripple (dB)
Astop  = 60;   % Stopband Attenuation (dB)

% Construct an FDESIGN object and call its ELLIP method.
h  = fdesign.bandpass('N,Fp1,Fp2,Ast1,Ap,Ast2', N, Fpass1, Fpass2, ...
                      Astop, Apass, Astop, Fs);
Hd = design(h, 'ellip');

% [EOF]
