/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.6 and Signal Processing Toolbox 8.2.
 * Generated on: 10-Sep-2020 20:07:02
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 10
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /opt/MATLAB/R2019a/extern/include/tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
#define MWSPT_NSEC 21
const int NL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1 };
const real32_T NUM[MWSPT_NSEC][3] = {
  {
     0.9112509489,              0,              0 
  },
  {
                1,   -1.746640921,              1 
  },
  {
     0.9112509489,              0,              0 
  },
  {
                1,   -1.998351097,              1 
  },
  {
     0.9209212661,              0,              0 
  },
  {
                1,   -1.709740639,              1 
  },
  {
     0.9209212661,              0,              0 
  },
  {
                1,   -1.998574853,              1 
  },
  {
     0.7950536013,              0,              0 
  },
  {
                1,   -1.555918932,              1 
  },
  {
     0.7950536013,              0,              0 
  },
  {
                1,   -1.999107003,              1 
  },
  {
     0.6014423966,              0,              0 
  },
  {
                1,  -0.2969917953,              1 
  },
  {
     0.6014423966,              0,              0 
  },
  {
                1,   -1.999849558,              1 
  },
  {
     0.0992468223,              0,              0 
  },
  {
                1,   -1.756656289,              1 
  },
  {
     0.0992468223,              0,              0 
  },
  {
                1,   -1.998278737,              1 
  },
  {
                1,              0,              0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1 };
const real32_T DEN[MWSPT_NSEC][3] = {
  {
                1,              0,              0 
  },
  {
                1,   -1.764648438,   0.9850866199 
  },
  {
                1,              0,              0 
  },
  {
                1,   -1.996677399,   0.9985726476 
  },
  {
                1,              0,              0 
  },
  {
                1,   -1.764165878,   0.9576524496 
  },
  {
                1,              0,              0 
  },
  {
                1,    -1.99325037,    0.995389998 
  },
  {
                1,              0,              0 
  },
  {
                1,   -1.768810153,   0.9015902281 
  },
  {
                1,              0,              0 
  },
  {
                1,   -1.981420875,   0.9844780564 
  },
  {
                1,              0,              0 
  },
  {
                1,   -1.809429526,   0.8580620289 
  },
  {
                1,              0,              0 
  },
  {
                1,   -1.932171702,   0.9403155446 
  },
  {
                1,              0,              0 
  },
  {
                1,   -1.766844273,   0.9964625239 
  },
  {
                1,              0,              0 
  },
  {
                1,   -1.997847676,   0.9996747971 
  },
  {
                1,              0,              0 
  }
};
