/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.4 and DSP System Toolbox 9.6.
 * Generated on: 07-Nov-2019 20:18:37
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 51
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 * Arithmetic        : fixed
 * Numerator         : s16,17 -> [-2.500000e-01 2.500000e-01)
 * Input             : s8,7 -> [-1 1)
 * Filter Internals  : Specify Precision
 *   Output          : s34,32 -> [-2 2)
 *   Product         : s15,16 -> [-2.500000e-01 2.500000e-01)
 *   Accumulator     : s20,16 -> [-8 8)
 *   Round Mode      : convergent
 *   Overflow Mode   : saturate
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /opt/MATLAB/R2018a/extern/include/tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
const int N = 51;
const int16_T NUM[51] = {
       -4,    -14,    -30,    -50,    -67,    -71,    -52,     -7,     53,
       99,     84,    -40,   -309,   -722,  -1223,  -1693,  -1971,  -1875,
    -1260,    -61,   1671,   3755,   5903,   7777,   9054,   9508,   9054,
     7777,   5903,   3755,   1671,    -61,  -1260,  -1875,  -1971,  -1693,
    -1223,   -722,   -309,    -40,     84,     99,     53,     -7,    -52,
      -71,    -67,    -50,    -30,    -14,     -4
};
