/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.3 and the DSP System Toolbox 8.6.
 * Generated on: 03-Apr-2017 20:41:57
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 51
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 * Arithmetic        : single
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /opt/MATLAB/R2014a/extern/include/tmwtypes.h 
 */
const int M = 51;
const float fir_coef_f[51] = {
  5.592278608e-19,0.0009115346475, 0.002566257026, 0.004935552832, 0.007773785852,
    0.01059850585,  0.01272476558,  0.01335929986,  0.01174670458, 0.007345449645,
  -1.828200179e-17,-0.009930168279, -0.02152111754, -0.03333944827, -0.04360775277,
   -0.05046388879, -0.05227541178, -0.04795460775, -0.03721324727, -0.02070234343,
                0,  0.02256275713,  0.04421758279,  0.06216706708,  0.07401690632,
    0.07815609872,  0.07401690632,  0.06216706708,  0.04421758279,  0.02256275713,
                0, -0.02070234343, -0.03721324727, -0.04795460775, -0.05227541178,
   -0.05046388879, -0.04360775277, -0.03333944827, -0.02152111754,-0.009930168279,
  -1.828200179e-17, 0.007345449645,  0.01174670458,  0.01335929986,  0.01272476558,
    0.01059850585, 0.007773785852, 0.004935552832, 0.002566257026,0.0009115346475,
  5.592278608e-19
};
