function Hd = kaiser_bandpass
%KAISER_BANDPASS Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.3 and the DSP System Toolbox 8.6.
% Generated on: 06-Jun-2017 22:41:17

% FIR Window Bandpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 44100;  % Sampling Frequency

N    = 500;       % Order
Fc1  = 300;      % First Cutoff Frequency
Fc2  = 3400;     % Second Cutoff Frequency
flag = 'scale';  % Sampling Flag
Beta = 7.5;      % Window Parameter
% Create the window vector for the design algorithm.
win = kaiser(N+1, Beta);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, [Fc1 Fc2]/(Fs/2), 'bandpass', win, flag);
Hd = dfilt.dffir(b);
set(Hd, 'Arithmetic', 'double');

% [EOF]
